server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tnews?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wangdan123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true